"""change timestamp columns to be timezone aware

Revision ID: 9eddc978166a
Revises: 5056ab90dc06
Create Date: 2026-07-13 21:54:51.442886

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eddc978166a"
down_revision: Union[str, Sequence[str], None] = "5056ab90dc06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employee",
        "birth_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        schema="demo",
    )
    op.alter_column(
        "employee",
        "hire_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        schema="demo",
    )
    op.alter_column(
        "invoice",
        "invoice_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        schema="demo",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice",
        "invoice_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        schema="demo",
    )
    op.alter_column(
        "employee",
        "hire_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        schema="demo",
    )
    op.alter_column(
        "employee",
        "birth_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        schema="demo",
    )
    # ### end Alembic commands ###
