name: persv

services:
  backend:
    build: apps/backend/
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - apps/backend/.env.production
    environment:
      - ENVIRONMENT=production
