// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteConnectionData, DeleteConnectionErrors, DeleteConnectionResponses, GetConnectionStatusData, GetConnectionStatusErrors, GetConnectionStatusResponses, GetHealthData, GetHealthResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutAllData, PostAuthLogoutAllResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthOtpData, PostAuthOtpErrors, PostAuthOtpResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostConnectionCustomData, PostConnectionCustomErrors, PostConnectionCustomResponses, PostConnectionDemoData, PostConnectionDemoErrors, PostConnectionDemoResponses, PostConnectionQueryData, PostConnectionQueryErrors, PostConnectionQueryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Check Health
 */
export const _get_Health = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Request a one-time password
 *
 * Sends a time-limited one-time password to the provided email address.
 * Use the returned code with `POST /auth/login` to authenticate.
 */
export const _post_AuthOtp = <ThrowOnError extends boolean = false>(options: Options<PostAuthOtpData, ThrowOnError>): RequestResult<PostAuthOtpResponses, PostAuthOtpErrors, ThrowOnError> => (options.client ?? client).post<PostAuthOtpResponses, PostAuthOtpErrors, ThrowOnError>({
    url: '/auth/otp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate with a one-time password
 *
 * Verifies the code sent to the provided email.
 * Creates a new account if the email is unrecognized.
 * Generates authentication tokens on success.
 */
export const _post_AuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke the current session
 *
 * Invalidates the refresh token stored in the HTTP-only cookie,
 * ending the current session. The client is responsible for discarding the access token.
 */
export const _post_AuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Revoke all sessions
 *
 * Invalidates all refresh tokens belonging to the user,
 * ending all sessions including the current one. The client is responsible
 * for discarding the access token.
 */
export const _post_AuthLogoutAll = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutAllData, ThrowOnError>): RequestResult<PostAuthLogoutAllResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout-all',
    ...options
});

/**
 * Rotate refresh token and issue new access token
 *
 * Validates the refresh token stored in the HTTP-only cookie,
 * issues a new access token, and rotates the refresh token.
 * The rotated refresh token is set as an HTTP-only cookie.
 */
export const _post_AuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>): RequestResult<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({ url: '/auth/refresh', ...options });

/**
 * Connect to the demo dataset
 *
 * Connect instantly to the built-in demo database. No credentials required.
 */
export const _post_ConnectionDemo = <ThrowOnError extends boolean = false>(options?: Options<PostConnectionDemoData, ThrowOnError>): RequestResult<PostConnectionDemoResponses, PostConnectionDemoErrors, ThrowOnError> => (options?.client ?? client).post<PostConnectionDemoResponses, PostConnectionDemoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/connection/demo',
    ...options
});

/**
 * Connect to a custom database
 *
 * Establish a database connection using the provided credentials.
 */
export const _post_ConnectionCustom = <ThrowOnError extends boolean = false>(options: Options<PostConnectionCustomData, ThrowOnError>): RequestResult<PostConnectionCustomResponses, PostConnectionCustomErrors, ThrowOnError> => (options.client ?? client).post<PostConnectionCustomResponses, PostConnectionCustomErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/connection/custom',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * View connection status
 *
 * Identify whether an active database connection is currently established.
 */
export const _get_ConnectionStatus = <ThrowOnError extends boolean = false>(options?: Options<GetConnectionStatusData, ThrowOnError>): RequestResult<GetConnectionStatusResponses, GetConnectionStatusErrors, ThrowOnError> => (options?.client ?? client).get<GetConnectionStatusResponses, GetConnectionStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/connection/status',
    ...options
});

/**
 * Disconnect from the database
 *
 * Terminate the active database connection and clear the associated session state.
 */
export const _delete_Connection = <ThrowOnError extends boolean = false>(options?: Options<DeleteConnectionData, ThrowOnError>): RequestResult<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/connection',
    ...options
});

/**
 * Query the database
 *
 * Ask a question in plain English and get an answer drawn directly from your data.
 */
export const _post_ConnectionQuery = <ThrowOnError extends boolean = false>(options: Options<PostConnectionQueryData, ThrowOnError>): RequestResult<PostConnectionQueryResponses, PostConnectionQueryErrors, ThrowOnError> => (options.client ?? client).post<PostConnectionQueryResponses, PostConnectionQueryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/connection/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
