// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AuthResponse
 *
 * Authentication credentials issued by the server.
 *
 * Attributes:
 * token: Short-lived JWT access token used for API authentication.
 * type: Authentication scheme used in the Authorization header.
 */
export type AuthResponse = {
    /**
     * Token
     *
     * Short-lived JWT access token used for API authentication.
     */
    token: string;
    /**
     * Type
     *
     * Authentication scheme used in the Authorization header.
     */
    type?: string;
};

/**
 * ConnectionConfig
 *
 * Database connection parameters provided by the user.
 */
export type ConnectionConfig = {
    /**
     * The database management system hosting the target database. Defaults to PostgreSQL.
     */
    dbms?: Dbms;
    /**
     * Username
     *
     * The username used to authenticate with the database server.
     */
    username: string;
    /**
     * Password
     *
     * The password used to authenticate with the database server.
     */
    password: string;
    /**
     * Host
     *
     * The hostname or IP address of the database server.
     */
    host: string;
    /**
     * Port
     *
     * The port number the database server is listening on.
     */
    port: number;
    /**
     * Db
     *
     * The name of the database to connect to.
     */
    db: string;
    /**
     * Schema
     *
     * The schema to set as the search path. Only applicable to database systems that support schemas,such as PostgreSQL. Leave empty for others.
     */
    schema?: string | null;
};

/**
 * ConnectionStatus
 */
export type ConnectionStatus = {
    /**
     * Connected
     */
    connected: boolean;
    /**
     * Database
     *
     * Name of the connected database, or 'null' if not connected.
     */
    database?: string | null;
};

/**
 * DBMS
 *
 * Supported database management systems and their SQLAlchemy URL schemes.
 */
export type Dbms = 'postgresql' | 'mysql' | 'mariadb' | 'sqlite' | 'oracle' | 'mssql';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 *
 * A generic health status response.
 */
export type HealthStatus = {
    /**
     * Status
     */
    status: string;
};

/**
 * OTPLoginRequest
 *
 * Request payload for completing OTP authentication.
 *
 * Attributes:
 * email: The user's email address.
 * Automatically validated and normalized.
 * code: The 6-digit one-time password sent to the user's email.
 */
export type OtpLoginRequest = {
    /**
     * Email
     *
     * The user's email address.
     */
    email: string;
    /**
     * Code
     *
     * The 6-digit one-time password sent to the user's email.
     */
    code: string;
};

/**
 * OTPRequest
 *
 * Request payload for initiating OTP authentication.
 *
 * Attributes:
 * email: The user's email address.
 * Automatically validated and normalized.
 */
export type OtpRequest = {
    /**
     * Email
     *
     * The user's email address.
     */
    email: string;
};

/**
 * OTPResponse
 *
 * Response returned after an OTP code is generated and sent.
 *
 * Attributes:
 * to: The recipient's email address. Included for confirmation only.
 * expires_in: The number of seconds until the OTP code expires.
 */
export type OtpResponse = {
    /**
     * To
     *
     * The email address to which the OTP code will be sent.
     */
    to: string;
    /**
     * Expires In
     *
     * Seconds until the OTP code expires.
     */
    expires_in: number;
};

/**
 * QueryRequest
 */
export type QueryRequest = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * QueryResponse
 *
 * Response containing the query result and the generated SQL statement.
 *
 * Attributes:
 * result (str): The result of the query.
 * sql (str): The SQL query executed to obtain the result.
 */
export type QueryResponse = {
    /**
     * Result
     *
     * The result of the query.
     */
    result: string;
    /**
     * Sql
     *
     * The SQL query that was generated and executed to get the result.
     */
    sql: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostAuthOtpData = {
    body: OtpRequest;
    path?: never;
    query?: never;
    url: '/auth/otp';
};

export type PostAuthOtpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAuthOtpError = PostAuthOtpErrors[keyof PostAuthOtpErrors];

export type PostAuthOtpResponses = {
    /**
     * Successful Response
     */
    200: OtpResponse;
};

export type PostAuthOtpResponse = PostAuthOtpResponses[keyof PostAuthOtpResponses];

export type PostAuthLoginData = {
    body: OtpLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostAuthLogoutAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout-all';
};

export type PostAuthLogoutAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostConnectionDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connection/demo';
};

export type PostConnectionDemoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostConnectionDemoError = PostConnectionDemoErrors[keyof PostConnectionDemoErrors];

export type PostConnectionDemoResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatus;
};

export type PostConnectionDemoResponse = PostConnectionDemoResponses[keyof PostConnectionDemoResponses];

export type PostConnectionCustomData = {
    body: ConnectionConfig;
    path?: never;
    query?: never;
    url: '/connection/custom';
};

export type PostConnectionCustomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostConnectionCustomError = PostConnectionCustomErrors[keyof PostConnectionCustomErrors];

export type PostConnectionCustomResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatus;
};

export type PostConnectionCustomResponse = PostConnectionCustomResponses[keyof PostConnectionCustomResponses];

export type GetConnectionStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connection/status';
};

export type GetConnectionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionStatusError = GetConnectionStatusErrors[keyof GetConnectionStatusErrors];

export type GetConnectionStatusResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatus;
};

export type GetConnectionStatusResponse = GetConnectionStatusResponses[keyof GetConnectionStatusResponses];

export type DeleteConnectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connection';
};

export type DeleteConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostConnectionQueryData = {
    body: QueryRequest;
    path?: never;
    query?: never;
    url: '/connection/query';
};

export type PostConnectionQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostConnectionQueryError = PostConnectionQueryErrors[keyof PostConnectionQueryErrors];

export type PostConnectionQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryResponse;
};

export type PostConnectionQueryResponse = PostConnectionQueryResponses[keyof PostConnectionQueryResponses];
